version: '2'
services:
  db:
    image: postgres:9.5.3
    ports:
      - "5432:5432"
    environment:
      - TERM=xterm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teambuilder_prod
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - TERM=xterm
      - PORT=4000
    depends_on:
      - db
  web:
    image: nginx:latest
    volumes:
      - ./ops/conf.d:/etc/nginx/conf.d
    environment:
      - TERM=xterm
    ports:
      - "80:80"
